led_control/urls.py
from django.urls import path
from .views import *

app_name = 'led_control'

urlpatterns = [
        path('', index, name='index'),
        path('update', update, name='update'),
]

rpi_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('led_control.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

led_control/models.py
from django.db import models

# Create your models here.

class led(models.Model):
        is_active = models.BooleanField(default=False)
        message = models.CharField(default='user has not provided any message', max_length=100)
        active_on = models.DateTimeField(auto_now_add=True)

        # reverse the order of DateTimeField so i can get the latest data
        class Meta:
                ordering = ['-active_on']

        def __str__(self):
                if self.is_active:
                        return 'GLOWING'
                return 'NOT GLOWING'

led_control/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import led
from gpiozero import LED
# Create your views here.

bulb = LED(15)

def index(request):
        template_name = 'led_control/index.html'
        # print(led.objects.all()[0], ' -> ', led.objects.all()[0].message)
        data = led.objects.all()[0]
        changeLedState(data.is_active)
        '''
        if data.is_active:
            bulb.on()
        else:
            bulb.off()
        '''
        context = {
                'data': data,
        }
        return render(request, template_name, context=context)
        # return HttpResponse('<h1>hello world<h1>')


def update(request):
        if request.method == 'POST':
                current_state = led()
                if request.POST.__contains__('switch'):
                    current_state.is_active = True
                if request.POST['message'] != '':
                        current_state.message = request.POST['message']
                current_state.save()
                # print(request.POST['message'])
                # print(request.POST.__contains__('switch'))
                return HttpResponseRedirect(reverse('led_control:index'))
            

def changeLedState(flag):
    print(flag, ' is here')
    if flag:
        bulb.on()
        return 'LED on'
    else:
        bulb.off()
        return 'LED off'

led_control/templates/led_control/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load static %}
    <link rel="stylesheet" href="{% static 'led_control/initial.css' %}">
    <link rel="stylesheet" href="{% static 'led_control/nav.css' %}">

    {% block static %}
    {% endblock %}

    <title>LED control</title>
</head>
<body>
    
    <!-- nav bar -->
    <nav>
        <h1>
            <a href="#">R-Pi Control</a>
        </h1>
        <label id="hamburgerLabel" for="hamburger"><span></span></label>
        <input type="checkbox" name="hamburger" id="hamburger" hidden>
        <div id="sideNav">
            <a href="#">LED</a>
        </div>
    </nav>

    {% block body %}
    {% endblock %}


</body>
</html>

led_control/templates/led_control/index.html
{% extends 'led_control/base.html' %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'led_control/index.css' %}">
{% endblock %}


{% block body %}
    <main>

        <section id="cards">

            <div class="card card1">
                <h1>About</h1>
                <table style="width:100%">
                    <tr>
                        <th>Device</th>
                        <td>Raspberry Pi 3</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>rootz491</td>
                    </tr>
                    <tr>
                        <th>LED pin</th>
                        <td>pin 15</td>
                    </tr>
                    <tr>
                        <th>Color</th>
                        <td style="color: green;">GREEN</td>
                        <!-- or red. if light is OFF -->
                        <!-- <td style="color: red;">RED</td> -->
                    </tr>
                    <tr>
                        <th>Power</th>
                        <td>1.5v</td>
                    </tr>
                </table>
            </div>

            <div class="card card2">
                <h1>Control</h1>
                <form action="{% url 'led_control:update' %}" method="POST">
                    {% csrf_token %}
                    <textarea name="message" id="message" cols="30" rows="10" placeholder="Leave a message here [optional]"></textarea>
                    <div class="switchWrapper">
                        <input type="checkbox" name="switch" id="switch"  {% if data.is_active %} checked=true {% endif %} hidden>
                        <label id="switchLabel" for="switch">
                            <span></span>
                        </label>
                    </div>
                    <div class="btnWrapper">
                        <button type="submit">send request</button>
                    </div>
                </form>
            </div>

        </section>

        <section id="state">
            <h1>CURRENT STATE:
                {% if data.is_active == True %}
                    <span style="color: green">{{ data }} <!-- ON --> </span>
                {% else %}
                    <span style="color: red">{{ data }} <!-- OFF --> </span>
                {% endif %}
            </h1>
        </section>

    </main>
{% endblock %}